### ISSUE TITLE
Variables in cookie definitions of requests don't get properly replaced when using the YAML format

### ISSUE THREAD

**Issue by NilsHasenbanck4758** [Xceptance/xlt-nocoding#23]
We currently use xlt-nocoding with the version 4.0.0.

When using the xlt-nocoding YAML format, variables are not replaced with their value content when used inside cookies of requests:

Given that the variable "A_COOKIE" has the content of "COOKIE CONTENT".

```yaml
- Action:
    Name: "DOESNT_WORK"
    Request:
      Url: "https://www.otto.de"
      Method: "GET"
      Cookies:
      - "a_cookie": "${A_COOKIE}"
```

Result: The cookie "a_cookie" will have the content "${A_COOKIE}" at runtime.

We would expect that variables in request cookie definition get properly replaced as it's the case for example the header definitions.

We currently use the following workaround of using the header to set the cookie correctly:

```yaml
- Action:
    Name: "WORKAROUND"
    Request:
      Url: "https://www.otto.de"
      Method: "GET"
      HEADERS:
      - "Cookie": "a_cookie=${A_COOKIE}"
```

Result: The cookie "a_cookie" will have the content "COOKIE CONTENT" at runtime.
