### ISSUE TITLE
Yaml Anchors not working

### ISSUE THREAD

**Issue by ckeiner** [Xceptance/xlt-nocoding#3]
Yaml offers anchors, which can later be references as follows:
```yaml
- Action : &id1
   Name : Reference Action
   Request :
       Url : https://localhost:8443/
       Method : GET
   Response :
       Httpcode : 200

- Action: *id1
```

As such, the second action should execute the same requests and validations as the first one but with different objects.
The first action parses correctly and without `&id1`.
However, the following exception is thrown when the second action is parsed:
```
com.fasterxml.jackson.core.JsonParseException: Action must either be emtpy or an ObjectNode, and not a TextNode
```
Using a debugger, it can be seen that the action is indeed parsed as TextNode containing the string `id1`.
According to [issue 85](https://github.com/FasterXML/jackson-dataformats-text/issues/85) and [issue 6](https://github.com/FasterXML/jackson-dataformats-text/issues/6) of the Jackson Dataformats repository, complex reference types will never be supported.

Possible solutions are to either parse with snakeyaml directly or to preprocess the file so these anchors and references are automatically resolved.
