### ISSUE TITLE
Missing reevaluation of dynamic data

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/xlt-nocoding#6]
In this example, all three requests see the same random number, because Url is evaluated initially and not when used.

```yaml
- Url: https://s3.eu-central-1.amazonaws.com/xlt-test-1/json/paypal.json?q=${RANDOM.Number(1,1000000)}

- Action:
    Name : Initial

- Action: &a
    Name : Followup

- Action: *a
- Action: *a
- Action: *a
- Action: *a
```

**Comment by ckeiner** [comment]
This behavior is intended. I edited the wiki for more clarity as follows:
Default Values
 * If the value of the definition of a Default Value contains a variable, it is resolved before the Default Value is stored.

Variables
 *   If the value of a variable contains other variables, they are resolved before the variable is stored. For example, in the following snippet the variable url is resolved to https://localhost:8443/posters/
```yaml
- Store :
    - var1 : posters/
    - url : https://localhost:8443/${var1}
```

Please recheck that this clarifies the intent.
